### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gitneeraj** [slab/quill#4338]
Please describe the a concise description and fill out the details below. It will help others efficiently understand your request and get to an answer instead of repeated back and forth. Providing a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve) will further increase your chances that someone can help.

**Steps for Reproduction**

created a basic CRA app. Visit the bare minimum reproducible repo at https://github.com/gitneeraj/test-quill-rte

**Expected behavior**:
when running the tests `yarn test` should mount the component and test should pass

**Actual behavior**:
Throws below error - 

/home/xx/personal/test-quill/node_modules/quill/quill.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import Quill, { Parchment, Range } from './core.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import RickTextEditor from "quill";
        | ^
      2 | import React, { forwardRef, useEffect, useLayoutEffect, useRef } from "react";
      3 | import "quill/dist/quill.snow.css";
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/Editor.js:1:1)
      at Object.<anonymous> (src/App.js:2:1)
      at Object.<anonymous> (src/App.test.js:2:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

**Platforms**:
node - 19 & 20
Include browser, operating system and respective versions

**Version**:

**Comment by cjnoname** [comment]
Same errror here

**Comment by luin** [comment]
I believe this is a duplicate of https://github.com/facebook/create-react-app/issues/9938.

**Comment by chrishoage** [comment]
@luin Not really - the issue appears to be that quill is defined as type: module but doesn't define a module 

See: https://nodejs.org/api/packages.html#dual-commonjses-module-packages

`main` should still point to a commonJS build
`module` should point to an ESM build 

Subpath exports can be used to define both require and module exports, and have types for them https://nodejs.org/api/packages.html#subpath-exports

As it stands today this package doesn't appear to fully support dual packages which makes integration with tools like jest challenging. 

Please consider using one of the dual package approaches outlined in the link

**Comment by gitneeraj** [comment]
@chrishoage - thank you for the input. Do you think there is any workaround getting the unit tests running with this package?
I tried to mock the entire package but it leads to whole lot of issues.

**Comment by chrishoage** [comment]
We used jest `moduleNameMapper` to point to the dist/quill.js file that is still in the package but not otherwise exposed via package.json

This allowed jest to use the "ADM" build of quill which jest can use with out any extra compilation on quill

**Comment by daiscog** [comment]
@chrishoage thanks for the hint, that's worked for us!

Specifically, in our `jest.config.ts`, we've added:

```ts
export default {
  //...
  moduleNameMapper: {
    '^quill$': 'node_modules/quill/dist/quill.js'
  },
}
```

**Comment by RichMatthews** [comment]
@daiscog I get 
```
 Could not locate module quill mapped as:
    node_modules/quill/dist/quill.js
```
when I use that code, anything else I need to do?

**Comment by RichMatthews** [comment]
@luin please chime in if you have anything else to add

**Comment by clepet** [comment]
We stumbled upon this problem too, big thank you to @chrishoage and @daiscog for the mentioned fix.

I just wanted to add that if your project is not only importing elements directly from `quill` (like `import Quill from 'quill';`) but also from subfolders (like `import Block, { BlockEmbed } from 'quill/blots/block';`) you need to use the following `moduleNameMapper` config:

```javascript
    moduleNameMapper: {
      '^quill$': 'node_modules/quill/dist/quill.js',
      '^quill/(.*)$': 'node_modules/quill/dist/quill.js'
    }
```

@luin this issue seems pretty critical to me, because without this config every jest test which uses quill imports throws errors. Are there any plans to fix this?
